export * from './Footer/Footer'
export * from './Header/Header'
export * from './Loading/Loading'
export * from './NavProfile/NavProfile'
export * from './UploadFile/UploadFile'
export * from './FavoritesNav/FavoritesNav'
export * from './CardPlayer/CardPlayer'
export * from './CardInTheGallery/CardInTheGallery'